### ISSUE TITLE
Install fails on OSX

### ISSUE THREAD

**Issue by asmod3us** [0k/shyaml#24]
Using `pip install shyaml --no-cache-dir`, the install fails with the below output. Not sure if the root cause is in shyaml?

Additional info: 
OSX version 10.11.6, 
❯ python --version
Python 2.7.12
❯ which python
/usr/local/bin/python

```
Collecting shyaml
  Downloading shyaml-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/65/y0kln7794j97nmtnxb607bbc0000gn/T/pip-build-MUekst/shyaml/setup.py", line 55, in <module>
        d2to1=True
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 664, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 694, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 875, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1100, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/var/folders/65/y0kln7794j97nmtnxb607bbc0000gn/T/easy_install-C_SSRW/d2to1-0.2.12.post1/setup.py", line 17, in <module>

      File "/var/folders/65/y0kln7794j97nmtnxb607bbc0000gn/T/easy_install-C_SSRW/d2to1-0.2.12.post1/d2to1/util.py", line 204, in cfg_to_args
      File "/var/folders/65/y0kln7794j97nmtnxb607bbc0000gn/T/easy_install-C_SSRW/d2to1-0.2.12.post1/d2to1/util.py", line 439, in wrap_commands
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 447, in get_command_list
        cmdclass = ep.resolve()
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/site-packages/pbr/testr_command.py", line 47, in <module>
        from testrepository import commands
    ImportError: No module named testrepository

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/65/y0kln7794j97nmtnxb607bbc0000gn/T/pip-build-MUekst/shyaml/
```

**Comment by szepeviktor** [comment]
There may be a pip problem on your side:
`testrepository` is available: https://pypi.python.org/pypi/testrepository and it is `OS Independent`.

**Comment by asmod3us** [comment]
No idea what caused this. Switched to a newer machine, running 10.12.1 and I can install again.

**Comment by vaab** [comment]
Thanks for both your report. Sorry if I was quite distant (I don't have much time currently, and I don't use MacOSX). Setuptools is quite brittle and I must say it wouldn't the first time that they would have introduce some regression. The fact that I'm using also a questionable stack don't help (d2to1 namely). These report are waiting in favor to simplify this, of course.
