### ISSUE TITLE
If no key exists in the file, get-value gives huge stack trace

### ISSUE THREAD

**Issue by kirhgoff** [0k/shyaml#34]
To use with big amounts of files I expect shyaml to report empty value for any key, but instead I am getting that:

cat somefile.yml | shyaml get-value abrakadabra
Traceback (most recent call last):
  File "/Users/klastovirya/.pyenv/versions/3.3.6/bin/shyaml", line 308, in aget
    value = dct[head]
KeyError: 'dsfdgfdfgf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/klastovirya/.pyenv/versions/3.3.6/bin/shyaml", line 378, in main
    value = mget(contents, key_value)
  File "/Users/klastovirya/.pyenv/versions/3.3.6/bin/shyaml", line 248, in mget
    return aget(dct, tokenize(key))
  File "/Users/klastovirya/.pyenv/versions/3.3.6/bin/shyaml", line 313, in aget
    % (head, ))
__main__.MissingKeyError
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/klastovirya/.pyenv/versions/3.3.6/bin/shyaml", line 429, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/klastovirya/.pyenv/versions/3.3.6/bin/shyaml", line 385, in main
    msg = str(exc.message)
AttributeError: 'MissingKeyError' object has no attribute 'message'

**Comment by vaab** [comment]
Thanks for the report. I'll probably implement something in this taste:
- catch all exception, only show the exception's title per default
- use environment variable and/or ``-d|--debug`` flag to allow displaying all the exceptions traceback
- Probably untie some very common and expected Exception to give a specially tailored message. The KeyError is one of them I'll have to investiguate.,
Meanwhile anyone can propose a PR.

**Comment by vaab** [comment]
Of course, while waiting for that, you can use:

    cat somefile.yml | shyaml get-value abrakadabra 2>/dev/null

To get exactly what you wanted. Just in case you didn't know.

**Comment by kirhgoff** [comment]
I wrote my own gem for my task, just wanted to let you know there is a problem
