### ISSUE TITLE
shyaml tries to construct objects from the input YAML

### ISSUE THREAD

**Issue by aodj** [0k/shyaml#40]
i wanted to use shyaml to iterate through a YAML file that contains encrypted Ansible Vault values, which are represented by objects, however the YAML loader tries to instantiate the corresponding object (represented by the `!vault` tag) and subsequently fails.

The script throws the following exception:

> yaml.constructor.ConstructorError: could not determine a constructor for the tag '!vault'

**Comment by varac** [comment]
I'm experiencing the same issue. Here's an example how shyaml breaks on a vault entry:

```
⏻  projects/yaml  » cat ansible-vault.yml
---
borgbackup_passphrase: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36663038343936383561366666353737613461653737363738636665306530326561363231616135
  3264653231353133363564326463643136373965636531380a396638326335313334343530353339
  61393232346439646538646331356665666465373662313734313439663465333166653764656664
  3363356663613563330a343366303030336236326138323965306564393861643031616161616632
  66373430336661383630376630306561663166313535346232383937356239653266323836383536
  3734336333393030653461396339613762373139666237643232


⏻  projects/yaml  » cat ansible-vault.yml| shyaml get-value 
Traceback (most recent call last):
  File "/home/varac/.local/bin/shyaml", line 459, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/varac/.local/bin/shyaml", line 397, in main
    contents = yaml.load(sys.stdin)
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/home/varac/.local/bin/shyaml", line 119, in construct_omap
    return MyOrderedDict(cls.construct_pairs(node))
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/home/varac/.local/venvs/shyaml/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!vault'
  in "<stdin>", line 2, column 24
```

I'll now check latest master if it fixes my issue.

**Comment by varac** [comment]
Ugh, with the same input file and latest master I now get:

```
⏻  projects/yaml  » cat ansible-vault.yml| shyaml get-value        
borgbackup_passphrase: !vault '$ANSIBLE_VAULT;1.1;AES256

  36663038343936383561366666353737613461653737363738636665306530326561363231616135

  3264653231353133363564326463643136373965636531380a396638326335313334343530353339

  61393232346439646538646331356665666465373662313734313439663465333166653764656664

  3363356663613563330a343366303030336236326138323965306564393861643031616161616632

  66373430336661383630376630306561663166313535346232383937356239653266323836383536

  3734336333393030653461396339613762373139666237643232

  '

```

**Comment by varac** [comment]
So this is obviously not fixed.

**Comment by varac** [comment]
@vaab Ping, any chance to get this fixed properly ?

**Comment by vaab** [comment]
Sorry for the (very) late answer... I'm obviously missing the point somewhere as for me, your last output seems to be what was expected ? might it be the formatting bugging you ? These are still the same YAML values... you can double check that by asking:

```bash
cat /tmp/ansible-vault.yml | shyaml -y get-value | shyaml get-value borgbackup_passphrase
```

If this is not the issue, can you tell me what you were expecting exactly ?
